### ISSUE TITLE
[meta-issue] finish up issues

### ISSUE THREAD

**Issue by alessandrofelder** [neuroinformatics-unit/software-practice-template#23]
TODO list for Monday afternoon - feel free to add/edit @lauraporta 

- [x] #16 
- [x] #18 
- [x] need a beginner function to refactor/DRY too?
- [x] fix all linking to issues
- [x] double-check issue numbering
- [x] make example issues for instructor to demo (write multiline string, write sanity check assertions)
